#!/bin/sh

/cx/cxdish fw-version
/cx/cxdish get-mode

sleep 5

ESmode=`i2cget -y 0 0x13 0x00`
if [ $ESmode -eq 0x03 ]; then
	echo "ES7243 IIC set."
else
	i2cset -y 0 0x13 0x00 0x03 i
fi


ps |grep ./caf_thin_client | grep -v grep
if [ $? -eq 0 ]; then 
	echo "caf run set."
else 
	/cx/caf_thin_client &
	sleep 1
fi

sleep 10


# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_200.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f200 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_300.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f300 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_400.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f400 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1
# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_440.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f440 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_500.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f500 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_600.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f600 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_700.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f700 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_800.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f800 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1


# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_900.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f900 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_1000.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f1000 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_1200.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f1200 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1


# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_1500.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f1500 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_2000.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f2000 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

# CX20921录音
arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/test_freq_2500.wav &

amixer sset Master 80%
amixer sset 'Speaker Function' 'headset-spk'
speaker-test -f2500 -tsine &

sleep 10
killall speaker-test
killall arecord
sleep 1

