#!/bin/sh
ESmode=`i2cget -y 0 0x13 0x00`
if [ $ESmode -eq 0x03 ]; then
	echo "ES7243 IIC set."
else
	i2cset -y 0 0x13 0x00 0x03 i
fi


ps |grep ./caf_thin_client | grep -v grep
if [ $? -eq 0 ]; then 
	echo "caf run set."
else 
	/cx/caf_thin_client &
	sleep 1
fi


echo "start test arecord."

arecord -D hw:1,0 -r 16000 -f S16_LE -c 1 /tmp/arecord_20s.wav &

sleep 20

echo "end test arecord."

killall arecord
